"""Add pseudouser table for capturing past salespeople who aren't true users

Revision ID: add-pseudouser
Revises: contract-invoice
Create Date: 2015-04-09 05:16:11.577874

"""

# revision identifiers, used by Alembic.
revision = 'add-pseudouser'
down_revision = 'contract-invoice'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pseudo_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=False),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pseudo_user')
    ### end Alembic commands ###
