"""Create the initial database schema

Revision ID: init
Revises: None
Create Date: 2015-03-31 01:13:05.662671

"""

# revision identifiers, used by Alembic.
revision = 'init'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type')
    )
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=False),
        sa.Column('last_name', sa.String(length=50), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('type', sa.Enum('admin', 'coord', 'exec', 'marketing', 'sales', name='UserType'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=True),
        sa.Column('type', sa.Enum('DIGITAL_AAA_DEV', 'DIGITAL_INDIE_DEV', 'DIGITAL_PUBLISHER', 'MEDIA', 'PRODUCTS', 'SCHOOLS_INSTITUTIONS', 'TABLETOP_DESIGNER', 'TABLETOP_INDIE_DEV', 'TABLETOP_PUBLISHER', name='SponsorType'), nullable=True),
        sa.Column('level', sa.Enum('INDIE', 'COPPER', 'SILVER', 'GOLD', 'PLATINUM', 'SERVICE', 'CHARITY', name='LevelType'), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('user_email',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('user_auth',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('reset_password_token', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_table('asset',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sponsor_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('type', sa.Enum('DIGITAL_BANNER', 'DIGITAL_MENU', 'LOGO', 'NEWSLETTER_HEADER', 'NEWSLETTER_SIDEBAR', 'NEWSLETTER_FOOTER', 'PROGRAM_QUARTER', 'PROGRAM_HALF', 'PROGRAM_WHOLE', 'PROGRAM_DOUBLE', 'WEBSITE_SIDEBAR', name='AssetType'), nullable=False),
        sa.Column('filename', sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sponsor_id', sa.Integer(), nullable=True),
        sa.Column('year', sa.Integer(), nullable=True),
        sa.Column('owner', sa.String(length=60), nullable=True),
        sa.Column('cash', sa.Integer(), nullable=True),
        sa.Column('inkind', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sponsor_id', sa.Integer(), nullable=True),
        sa.Column('link', sa.String(length=2000), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sponsor_id', sa.Integer(), nullable=True),
        sa.Column('email', sa.String(length=80), nullable=True),
        sa.Column('name', sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('contact')
    op.drop_table('info')
    op.drop_table('deal')
    op.drop_table('asset')
    op.drop_table('user_auth')
    op.drop_table('user_email')
    op.drop_table('sponsor')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
