"""empty message

Revision ID: add-usages
Revises: add-exec
Create Date: 2015-07-07 01:55:08.118484

"""

# revision identifiers, used by Alembic.
revision = 'add-usages'
down_revision = 'add-exec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('usages', sa.Integer(), nullable=False, server_default=sa.sql.expression.text("0")))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'usages')
    ### end Alembic commands ###
