"""Create tables to track invoices and contracts

Revision ID: 35a062df1f7
Revises: populate
Create Date: 2015-04-02 01:45:03.281993

"""

# revision identifiers, used by Alembic.
revision = 'contract-invoice'
down_revision = 'populate'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
	    sa.Column('id', sa.Integer(), nullable=False),
	    sa.Column('deal_id', sa.Integer(), nullable=True),
	    sa.Column('sent', sa.Date(), nullable=True),
	    sa.Column('received', sa.Date(), nullable=True),
	    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
	    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
	    sa.Column('id', sa.Integer(), nullable=False),
	    sa.Column('deal_id', sa.Integer(), nullable=True),
	    sa.Column('sent', sa.Date(), nullable=True),
	    sa.Column('received', sa.Date(), nullable=True),
	    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
	    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    op.drop_table('invoice')
    ### end Alembic commands ###
