"""Move the colmns in Info into Sponsor.

Revision ID: merge-info
Revises: contract-invoice
Create Date: 2015-04-11 20:00:03.370690

"""

# revision identifiers, used by Alembic.
revision = 'merge-info'
down_revision = 'contract-invoice'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    op.add_column('sponsor', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('sponsor', sa.Column('link', sa.String(length=2000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsor', 'link')
    op.drop_column('sponsor', 'description')
    op.create_table('info',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('sponsor_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('link', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.id'], name='info_sponsor_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='info_pkey')
    )
    ### end Alembic commands ###
