"""Added ready column to Invoice and Contract

Revision ID: request-ready
Revises: merge-info
Create Date: 2015-04-11 20:18:32.350892

"""

# revision identifiers, used by Alembic.
revision = 'request-ready'
down_revision = 'merge-info'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from sponsortracker import model


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('ready', sa.Boolean(), nullable=True, default=False))
    op.add_column('invoice', sa.Column('ready', sa.Boolean(), nullable=True, default=False))
    ### end Alembic commands ###
    
    # Creating a new session for modifying data is necessary to prevent
    # PostgreSQL from locking up due to being in a transaction.
    Session = sessionmaker(bind=op.get_bind())
    session = Session()
    
    for deal in session.query(model.Deal).all():
        if not deal.contract:
            deal.contract = model.Contract(deal.id)
        if not deal.invoice:
            deal.invoice = model.Invoice(deal.id)
    
    session.commit()

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'ready')
    op.drop_column('contract', 'ready')
    ### end Alembic commands ###
