"""empty message

Revision ID: move-assets
Revises: remove-roles
Create Date: 2015-04-25 18:46:42.100555

"""

# revision identifiers, used by Alembic.
revision = 'move-assets'
down_revision = 'remove-roles'

import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from sponsortracker import model

AssetHelper = sa.Table(
    "asset",
    sa.MetaData(),
    sa.Column("id", sa.Integer, primary_key=True),
    sa.Column("deal_id", sa.Integer, sa.ForeignKey('deal.id')),
    sa.Column("sponsor_id", sa.Integer, sa.ForeignKey('sponsor.id')),
    sa.Column("date", sa.Date),
    sa.Column('type', sa.Enum('DIGITAL_BANNER', 'DIGITAL_MENU', 'LOGO', 'NEWSLETTER_HEADER', 'NEWSLETTER_SIDEBAR', 'NEWSLETTER_FOOTER', 'PROGRAM_QUARTER', 'PROGRAM_HALF', 'PROGRAM_WHOLE', 'PROGRAM_DOUBLE', 'WEBSITE_SIDEBAR', name='AssetType'), nullable=False),
    sa.Column("filename", sa.String(256), nullable=False)
)

DealHelper = sa.Table(
    "deal",
    sa.MetaData(),
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.Column('inkind', sa.Integer(), nullable=True),
    sa.Column("level", sa.Enum('INDIE', 'COPPER', 'SILVER', 'GOLD', 'PLATINUM', 'SERVICE', 'CHARITY', name='LevelType'), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.id'])
)

SponsorHelper = sa.Table(
    "sponsor",
    sa.MetaData(),
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('type', sa.Enum('DIGITAL_AAA_DEV', 'DIGITAL_INDIE_DEV', 'DIGITAL_PUBLISHER', 'MEDIA', 'PRODUCTS', 'SCHOOLS_INSTITUTIONS', 'TABLETOP_DESIGNER', 'TABLETOP_INDIE_DEV', 'TABLETOP_PUBLISHER', name='SponsorType'), nullable=True),
    sa.Column('level', sa.Enum('INDIE', 'COPPER', 'SILVER', 'GOLD', 'PLATINUM', 'SERVICE', 'CHARITY', name='LevelType'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True)
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('level', sa.Enum('INDIE', 'COPPER', 'SILVER', 'GOLD', 'PLATINUM', 'SERVICE', 'CHARITY', name='LevelType', native_enum=False), nullable=True))
    op.add_column('asset', sa.Column('deal_id', sa.Integer(), nullable=True))
    op.drop_constraint('asset_sponsor_id_fkey', 'asset', type_='foreignkey')
    op.create_foreign_key('asset_deal_id_fkey', 'asset', 'deal', ['deal_id'], ['id'])
    
    for asset in op.get_bind().execute(AssetHelper.select()):
        op.get_bind().execute(
            AssetHelper.update()
                .values(deal_id=AssetHelper.c.sponsor_id)
                .where(AssetHelper.c.id == asset.id)
        )
    
    for sponsor in op.get_bind().execute(SponsorHelper.select()):
        op.get_bind().execute(
            DealHelper.update()
                .values(level=sponsor.level)
                .where(DealHelper.c.sponsor_id == sponsor.id)
                .where(DealHelper.c.year == datetime.date.today().year)
        )
    
    op.drop_column('asset', 'sponsor_id')
    op.drop_column('sponsor', 'level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsor', sa.Column('level', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('sponsor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    for asset in op.get_bind().execute(AssetHelper.select()):
        op.get_bind().execute(
            AssetHelper.update()
                .values(sponsor_id=AssetHelper.c.deal_id)
                .where(AssetHelper.c.id == asset.id)
        )

    for deal in op.get_bind().execute(DealHelper.select().where(DealHelper.c.year == datetime.date.today().year)):
        op.get_bind().execute(
            SponsorHelper.update()
                .values(level=deal.level)
                .where(SponsorHelper.c.id == deal.sponsor_id)
        )
    
    op.drop_column('deal', 'level')
    op.drop_constraint('asset_deal_id_fkey', 'asset', type_='foreignkey')
    op.create_foreign_key('asset_sponsor_id_fkey', 'asset', 'sponsor', ['sponsor_id'], ['id'])
    op.drop_column('asset', 'deal_id')
    ### end Alembic commands ###
